# Change these first
owner: StrikeFinancial # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Site
    url: https://strike.financial
  - name: Login
    url: https://login.strike.financial
  - name: Signup
    url: https://signup.strike.financial
  - name: App
    url: https://app.strike.financial

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.strike.financial
  # baseUrl: /status
  logoUrl: https://assets.strike.financial/banner.png
  name: Strike Status
  introTitle: "Strike System Status"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Strike
      href: https://strike.financial

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
